### ISSUE TITLE
No problem with korean and japanese input

### ISSUE THREAD

**Issue by crocket** [s-n-g/python-curses-input#1]
I used fcitx-hangul for korean and fcitx-anthy for japanese.

**Comment by s-n-g** [comment]
Great!
Both python 2 and 3?

**Comment by crocket** [comment]
Yes. But, Ctrl+Space crashes ncurses. Ctrl+Space crashes ranger file manager too because ranger uses ncurses.

```
Traceback (most recent call last):
  File "./curses-test-input.py", line 89, in <module>
    curses.wrapper(getcodes)
  File "/usr/lib64/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "./curses-test-input.py", line 84, in getcodes
    win.addstr(ch)
TypeError: str
```

**Comment by s-n-g** [comment]
Same here with 3.7:
```
Traceback (most recent call last):
  File "./curses-test-input.py", line 89, in <module>
    curses.wrapper(getcodes)
  File "/usr/lib/python3.7/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "./curses-test-input.py", line 84, in getcodes
    win.addstr(ch)
ValueError: embedded null character
```
The good thing is that it seems to be a curses bug
I will look into it...

**Comment by s-n-g** [comment]
ok, I think I got it. Ctrl+Space is ignored.
Can you give it a try?

**Comment by crocket** [comment]
It doesn't crash, but I'm not sure if ignoring Ctrl+Space is a good idea if you want to map Ctrl+Space to some action.

**Comment by s-n-g** [comment]
Yes, I see what you mean... But there's no other way...
Actually, I am not ignoring Ctrl+Space

Ctrl+Space returns a zero byte (null), and I'm ignoring this one
I do not know if any other key combination returns a zero byte, some may do

But, on the other hand, why use Ctrl+Space while typing (insetring text) on a terminal?
Mapping it to an action is a different thing; you don't have to "print" it in curses (this is what crushes it), you just have to detect it and act accordingly

**Comment by crocket** [comment]
I type ctrl+space by mistake sometimes.

**Comment by s-n-g** [comment]
Oh, I see, so you crush programs regularly :smile: 

But again, if not intended, no problem to be ignored :smiley:

**Comment by s-n-g** [comment]
BTW, if you build ```ranger``` from github, the Ctrl+Space issue is now fixed (merged in master)

**Comment by crocket** [comment]
Does ranger also ignore zero byte to work around ncurses bug?

**Comment by s-n-g** [comment]
Yes, same thing there too
https://github.com/ranger/ranger/pull/1452
